name:                hw3
version:             0.1.0.0
github:              "github/fp-ctd-itmo/homework-3-flydzen"
license:             BSD3
author:              "Vasilyev Aleksey"
maintainer:          "flydzen@gmail.com"
copyright:           "none"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fp-hw3#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline >=0.8.1.2
- megaparsec
- prettyprinter
- prettyprinter-ansi-terminal
- scientific
- parser-combinators
- text
- containers
- bytestring
- zlib
- serialise
- time
- mtl
- directory
- random
library:
  source-dirs: src

executables:
  fp-hw3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3

tests:
  fp-hw3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3
